### ISSUE TITLE
Create a blog function for the site

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/site#5]
Ideas and suggestions for this welcomed!

**Comment by dannycolin** [comment]
You can assign that issue to me if you want ;)

**Comment by dannycolin** [comment]
And voilà! I've opened a pull request for the first draft of this issue. I'll need to do some reorganization in the layout (moving the header code to its own include file to avoid duplicate code). 

Feel free to suggest things [here](https://github.com/OpenScienceMOOC/site/pull/8)

**Comment by Protohedgehog** [comment]
Quick one - invited you to join the project now! I don't think it's possible to invite someone from outside otherwise.

Awesme, thanks for this! Will review the request very shortly :)

**Comment by Kevin-Mattheus-Moerman** [comment]
Cool. Let me know if I can help. 

BTW I based the website on the [Project Pages Jekyll template](http://jekyllthemes.org/themes/project-pages/) (see this [demo](http://projectpages.github.io/project-pages/)). That template had blog functionality. However I did not like it initially and basically took it out (on my own [personal page](https://kevinmoerman.org/), which stems from the same template, I changed it to a simpler "blog" where it renders cards for the posts on the front pages and lists the blog in the navigation menu as well, however I removed the search functionality stuff). 
If you like the way the old Project Pages template handled blog posts we can try to work it back in as well. If you like the simple blog style of my personal page I can also easily add that. 

I have zero time over the next two weeks (due to my move back to Europe) but let me know if you need help.

**Comment by Protohedgehog** [comment]
Awesome, thanks Kevin. It's here now, what do you think? https://opensciencemooc.github.io/site/uncategorized/2018/08/02/welcome-post/ Does the job nicely.

Oh, is that a congrats that you're moving back? Where are you landing? :)
